// console/src/layouts/MainLayout.tsx
import { Outlet, useNavigate, useLocation } from 'react-router-dom';
import { Layout, Menu, Avatar, Space, Breadcrumb, Badge, Button, Dropdown } from 'antd';
import type { ReactNode } from 'react';
import {
  DashboardOutlined,
  FileTextOutlined,
  BranchesOutlined,
  UserOutlined,
  AuditOutlined,
  AppstoreOutlined,
  CloudServerOutlined,
  GlobalOutlined,
  BellOutlined,
  RightOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  LogoutOutlined,
  SettingOutlined,
  SunOutlined,
  MoonOutlined,
  DesktopOutlined,
} from '@ant-design/icons';
import { useUserStore, useAppStore } from '../stores';
import type { Theme } from '../stores/app';

const { Header, Sider, Content, Footer } = Layout;

const menuItems = [
  { path: '/dashboard', name: '仪表盘', icon: <DashboardOutlined /> },
  { path: '/definitions', name: '流程定义', icon: <FileTextOutlined /> },
  { path: '/processes', name: '流程实例', icon: <BranchesOutlined /> },
  { path: '/runners', name: '组件管理', icon: <CloudServerOutlined /> },
  { path: '/endpoints', name: '系统配置', icon: <GlobalOutlined /> },
  { path: '/users', name: '用户管理', icon: <UserOutlined /> },
  { path: '/audit-logs', name: '审计日志', icon: <AuditOutlined /> },
];

const routeNameMap: Record<string, string> = {
  '/dashboard': '仪表盘',
  '/definitions': '流程定义',
  '/processes': '流程实例',
  '/runners': '组件管理',
  '/endpoints': '系统配置',
  '/users': '用户管理',
  '/audit-logs': '审计日志',
};

const MainLayout = () => {
  const navigate = useNavigate();
  const location = useLocation();

  const { user, logout } = useUserStore();
  const { sidebarCollapsed, toggleSidebar, theme: appTheme, setTheme } = useAppStore();

  const activeMenuKey = menuItems.find((item) => location.pathname.startsWith(item.path))?.path || '/dashboard';

  const getInitials = (name: string) => {
    return name.slice(0, 2).toUpperCase();
  };

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  const userMenuItems = [
    {
      key: 'profile',
      icon: <UserOutlined />,
      label: '个人信息',
    },
    {
      key: 'settings',
      icon: <SettingOutlined />,
      label: '系统设置',
    },
    {
      type: 'divider' as const,
    },
    {
      key: 'logout',
      icon: <LogoutOutlined />,
      label: '退出登录',
      danger: true,
      onClick: handleLogout,
    },
  ];

  const themeOptions: { value: Theme; label: string; icon: ReactNode }[] = [
    { value: 'light', label: '浅色', icon: <SunOutlined /> },
    { value: 'dark', label: '深色', icon: <MoonOutlined /> },
    { value: 'system', label: '跟随系统', icon: <DesktopOutlined /> },
  ];

  const getCurrentThemeIcon = () => {
    if (appTheme === 'dark') {
      return <MoonOutlined />;
    }
    if (appTheme === 'light') {
      return <SunOutlined />;
    }
    return <DesktopOutlined />;
  };

  const sideMenuItems = [
    {
      type: 'group' as const,
      label: '流程管理',
      children: menuItems
        .filter((item) => ['/dashboard', '/definitions', '/processes', '/runners'].includes(item.path))
        .map((item) => ({
          key: item.path,
          icon: item.icon,
          label: item.name,
          onClick: () => navigate(item.path),
        })),
    },
    {
      type: 'group' as const,
      label: '系统管理',
      children: menuItems
        .filter((item) => ['/endpoints', '/users', '/audit-logs'].includes(item.path))
        .map((item) => ({
          key: item.path,
          icon: item.icon,
          label: item.name,
          onClick: () => navigate(item.path),
        })),
    },
  ];

  return (
    <Layout className="gflow-main-layout">
      <Sider
        trigger={null}
        collapsible
        collapsed={sidebarCollapsed}
        className="gflow-main-sider"
        theme="dark"
        width={240}
        collapsedWidth={88}
      >
        <div className={`gflow-main-logo ${sidebarCollapsed ? 'is-collapsed' : ''}`}>
          <AppstoreOutlined className="gflow-main-logo-icon" />
          {!sidebarCollapsed && 'GFlow Admin'}
        </div>
        <Menu
          theme="dark"
          mode="inline"
          selectedKeys={[activeMenuKey]}
          items={sideMenuItems}
        />
      </Sider>
      <Layout className="gflow-main-frame" style={{ marginLeft: sidebarCollapsed ? 88 : 240 }}>
        <Header className="gflow-main-header">
          <Space size={8}>
            <Button
              type="text"
              className="gflow-main-collapse-btn"
              icon={sidebarCollapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
              onClick={toggleSidebar}
            />
            <Breadcrumb
              separator={<RightOutlined style={{ fontSize: 10, color: '#cbd5e1' }} />}
              items={[
                { title: '控制台' },
                { title: routeNameMap[location.pathname] || '详情' },
              ]}
            />
          </Space>
          <Space size={18}>
            <Dropdown
              menu={{
                items: themeOptions.map((option) => ({
                  key: option.value,
                  icon: option.icon,
                  label: option.label,
                })),
                onClick: ({ key }) => setTheme(key as Theme),
              }}
              trigger={['click']}
            >
              <Button type="text" className="gflow-main-header-theme-btn" icon={getCurrentThemeIcon()}>
                {themeOptions.find((item) => item.value === appTheme)?.label || '主题'}
              </Button>
            </Dropdown>
            <Badge dot>
              <BellOutlined className="gflow-main-header-bell" />
            </Badge>
            <div className="gflow-main-header-divider" />
            <span className="gflow-main-header-date">
              {new Date().toLocaleDateString('zh-CN', {
                year: 'numeric',
                month: '2-digit',
                day: '2-digit',
                weekday: 'long',
              })}
            </span>
            <Dropdown
              menu={{
                items: userMenuItems,
              }}
              trigger={['click']}
            >
              <div className="gflow-main-header-user">
                <Avatar className="gflow-main-user-avatar">{getInitials(user?.username || 'U')}</Avatar>
                <span>{user?.username || 'Admin User'}</span>
              </div>
            </Dropdown>
          </Space>
        </Header>
        <Content className="gflow-main-content">
          <div className="gflow-main-content-inner">
            <Outlet />
          </div>
        </Content>
        <Footer className="gflow-main-footer">
          <span>© 2024 GFlow Automation Systems. 保留所有权利。</span>
          <Space size={20}>
            <a>文档</a>
            <a>支持</a>
            <a>API 参考</a>
          </Space>
        </Footer>
      </Layout>
    </Layout>
  );
};

export default MainLayout;

// console/src/layouts/MainLayout.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useAppStore, useUserStore } from '@/stores'
import { Button } from '@/components/ui/button'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import {
  LayoutDashboard,
  FileText,
  GitBranch,
  Pencil,
  Server,
  Users,
  ScrollText,
  ChevronLeft,
  ChevronRight,
  LogOut,
  User,
  Settings,
  Workflow,
  Globe,
  Sun,
  Moon,
  Monitor,
} from 'lucide-vue-next'
import { cn } from '@/lib/utils'
import type { Theme } from '@/stores/app'

const router = useRouter()
const route = useRoute()
const appStore = useAppStore()
const userStore = useUserStore()

const menuItems = [
  { path: '/dashboard', name: '仪表盘', icon: LayoutDashboard },
  { path: '/definitions', name: '流程定义', icon: FileText },
  { path: '/processes', name: '流程实例', icon: GitBranch },
  { path: '/system', name: '组件管理', icon: Server },
  { path: '/endpoints', name: '接口管理', icon: Globe },
  { path: '/users', name: '用户管理', icon: Users },
  { path: '/audit-logs', name: '审计日志', icon: ScrollText },
]

const breadcrumbs = computed(() => {
  const matched = route.matched.filter(r => r.meta?.title)
  return matched.map(r => ({
    title: r.meta?.title as string,
    path: r.path,
  }))
})

function handleLogout() {
  userStore.logout()
  router.push('/login')
}

function getInitials(name: string) {
  return name.slice(0, 2).toUpperCase()
}

const themeOptions: { value: Theme; label: string; icon: typeof Sun }[] = [
  { value: 'light', label: '浅色', icon: Sun },
  { value: 'dark', label: '深色', icon: Moon },
  { value: 'system', label: '系统', icon: Monitor },
]

function handleThemeChange(theme: Theme) {
  appStore.setTheme(theme)
}
</script>

<template>
  <div class="min-h-screen flex bg-background">
    <!-- Sidebar -->
    <aside
      :class="cn(
        'fixed left-0 top-0 z-40 h-screen bg-card border-r transition-all duration-300',
        appStore.sidebarCollapsed ? 'w-16' : 'w-64'
      )"
    >
      <!-- Logo -->
      <div class="h-16 flex items-center justify-between px-2 border-b">
        <div class="flex items-center gap-3 overflow-hidden w-full" :class="appStore.sidebarCollapsed ? 'justify-center' : ''">
          <div class="w-10 h-10 bg-gflow-primary rounded-xl flex items-center justify-center text-white shrink-0">
            <Workflow class="w-6 h-6" />
          </div>
          <span
            v-if="!appStore.sidebarCollapsed"
            class="text-xl font-bold whitespace-nowrap"
          >
            GFlow
          </span>
        </div>
      </div>

      <!-- Navigation -->
      <nav class="flex-1 py-4 px-2 space-y-1 overflow-y-auto">
        <router-link
          v-for="item in menuItems"
          :key="item.path"
          :to="item.path"
          :class="cn(
            'flex items-center gap-3 py-2.5 rounded-lg text-sm font-medium transition-colors',
            appStore.sidebarCollapsed ? 'px-2 justify-center' : 'px-3',
            route.path === item.path || route.path.startsWith(item.path + '/')
              ? 'bg-gflow-primary/10 text-gflow-primary'
              : 'text-muted-foreground hover:bg-accent hover:text-accent-foreground'
          )"
        >
          <component :is="item.icon" class="w-5 h-5 shrink-0" />
          <span v-if="!appStore.sidebarCollapsed" class="whitespace-nowrap">
            {{ item.name }}
          </span>
        </router-link>
      </nav>

      <!-- Collapse button -->
      <div class="absolute bottom-4 left-0 right-0 px-2">
        <Button
          variant="ghost"
          size="icon"
          :class="cn('h-10', appStore.sidebarCollapsed ? 'w-full' : 'w-full')"
          @click="appStore.toggleSidebar"
        >
          <ChevronLeft v-if="!appStore.sidebarCollapsed" class="w-5 h-5" />
          <ChevronRight v-else class="w-5 h-5" />
        </Button>
      </div>
    </aside>

    <!-- Main content -->
    <div
      :class="cn(
        'flex-1 flex flex-col transition-all duration-300',
        appStore.sidebarCollapsed ? 'ml-16' : 'ml-64'
      )"
    >
      <!-- Header -->
      <header class="h-16 bg-card border-b flex items-center justify-between px-6 sticky top-0 z-30">
        <!-- Breadcrumbs -->
        <nav class="flex items-center gap-2 text-sm">
          <span class="text-muted-foreground">首页</span>
          <template v-for="(crumb, index) in breadcrumbs" :key="crumb.path">
            <span class="text-muted-foreground">/</span>
            <span
              :class="index === breadcrumbs.length - 1 ? 'text-foreground font-medium' : 'text-muted-foreground'"
            >
              {{ crumb.title }}
            </span>
          </template>
        </nav>

        <div class="flex items-center gap-2">
          <!-- Theme toggle -->
          <DropdownMenu>
            <DropdownMenuTrigger as-child>
              <Button variant="ghost" size="icon">
                <Sun v-if="appStore.theme === 'light'" class="w-5 h-5" />
                <Moon v-else-if="appStore.theme === 'dark'" class="w-5 h-5" />
                <Monitor v-else class="w-5 h-5" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuItem
                v-for="option in themeOptions"
                :key="option.value"
                :class="appStore.theme === option.value ? 'bg-accent' : ''"
                @click="handleThemeChange(option.value)"
              >
                <component :is="option.icon" class="w-4 h-4 mr-2" />
                {{ option.label }}
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>

          <!-- User menu -->
          <DropdownMenu>
            <DropdownMenuTrigger as-child>
              <Button variant="ghost" class="flex items-center gap-2 px-2">
                <Avatar class="w-8 h-8">
                  <AvatarImage :src="userStore.user?.avatar" />
                  <AvatarFallback class="bg-gflow-primary text-white text-xs">
                    {{ getInitials(userStore.username || 'U') }}
                  </AvatarFallback>
                </Avatar>
                <span class="hidden md:inline">{{ userStore.username }}</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" class="w-48">
              <DropdownMenuLabel>
                <div class="flex flex-col">
                  <span>{{ userStore.username }}</span>
                  <span class="text-xs text-muted-foreground font-normal">
                    {{ userStore.user?.email }}
                  </span>
                </div>
              </DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>
                <User class="w-4 h-4 mr-2" />
                个人信息
              </DropdownMenuItem>
              <DropdownMenuItem>
                <Settings class="w-4 h-4 mr-2" />
                系统设置
              </DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem @click="handleLogout" class="text-destructive">
                <LogOut class="w-4 h-4 mr-2" />
                退出登录
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>

      <!-- Page content -->
      <main class="flex-1 p-6 overflow-auto bg-muted/30">
        <router-view v-slot="{ Component }">
          <transition name="fade" mode="out-in">
            <component :is="Component" />
          </transition>
        </router-view>
      </main>
    </div>
  </div>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
